### ISSUE TITLE
Real-Time Monitor Mode for a BT connected to ROS2 

### ISSUE THREAD

**Issue by cpaniagua1** [BehaviorTree/behaviortree_cpp_v3-release#4]
Hi! 
I have programmed a simple BT to coordinate a use case developed in ROS2 Humble. The tree works fine but I can't monitor its execution in real time. I'm using the following versions:

- Groot 2 version 1.6.1
- BehaviorTree_cpp_v3 version 3.8.7
- ZMQ3 version 4.3.4

When I try to connect Groot2 with the Tree I get this error: Disconnected with error:  "Fetch FullTree: Wrong ReplyHeader"

**Comment by facontidavide** [comment]
Hi,

Groot2 is **NOT** compatible with the ZMQ publisher by BT.CPP 3.8.

For some technical reason related to the data structure used to represent treesand subtrees, I decided that it would be too hard to  support both version 3.X and 4.X.

Therefore, this a WONTFIX
